theme: jekyll-theme-minimal
title: Ismael Garcia
description: A short description of your site's purpose
logo: [https://avatars3.githubusercontent.com/u/1107432?s=400&u=9355d4f11c4260b09b458d17847789ba2fa63ff2&v=4]
