title: Ismael Garcia
logo: /assets/img/logo.png #/assets/img/logo.png /assets/img/logo.png
phone_contact: dummy_phone
web_mode: true
resume_mode: false
application: OTHER #APPLE #ARM,GEN,HF,TTP,MSFT,AMZN,DPMND,AZN,SMSNG
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
