title: Ismael Garcia
# Printed resume: disable logo / Online: enable logo
logo: /assets/img/logo.png 
application: DPMND # MSFT,AMZN,DPMND,AZN
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
